### PR TITLE
added social particle swarm example in examples directory

### PR DESCRIPTION
**Pull request by jiruhameru**
The social particle swarm (sps) model is a particles-based simulation of social agents interacting in a 3D Cartesian space through kinematics (attraction or repulsion) within an iterated prisoners dilemma game. There are two types of particles: Cooperators (blue) and defectors (red), each particle seeks to maximize its total payoff it receives from its neighbors, and it gets closer to those who offer benefit, and pulls away from those who don't. In the send, the simulation shows formation of clusters (composed by a majority of cooperators), followed by their explosions (due to being overpopulated by defectors).

### CODE REVIEW

**Comment by Robadob** [comment]
Why are `examples/learning_SPS/src/model/XSLTProcessor.exe`, `examples/learning_SPS/src/model/functions.xslt` included in the commit?
Are these modified from the original versions already available at `FLAMEGPU/tools/XSLTProcessor.exe`, `FLAMEGPU/templates/functions.xslt` respectively? (if so, how/why?)

For inclusion, it will require addition of a visual studio project file (as seen in all the other examples). I should be able to add that later in the week when I have more time if you're unable, at which point I'll also give the model a closer look.

Thanks

**Comment by jiruhameru** [comment]
No both `examples/learning_SPS/src/model/XSLTProcessor.exe`, and  `examples/learning_SPS/src/model/functions.xslt` are duplicates, I forgot to remove them from the `examples/learning_SPS` folder. Apologies. 

About the visual studio project file, I compiled the example in linux from command line, but I will try to re-create the project in Visual studio.

**Comment by ptheywood** [comment]
> The project appears to be missing an initial states file (an example that a user can't test is unsuitable), I tried running it without an initial states file and the visualisation remained empty. Following other examples this should be placed in examples/learning_SPS/Iterations and be named 0.xml.

`.xml` files are ignored by git (to avoid accidentally adding the dynamically generated xml files, so you will nee do to use `git add -f /path/to/0.xml`

**Comment by jiruhameru** [comment]
I made the changes. I accidentally deleted the project, so I had to fork it again, sorry about that.

**Comment by Robadob** [comment]
Do you mean you need to create a new pull request?

It currently says 'unknown repository'
image
Which i haven't seen before.

**Comment by jiruhameru** [comment]
Yes, I think so

**Comment by Robadob** [comment]
That's fine, create a new PR and reference this one with #277 (and then close this one).

**Comment by jiruhameru** [comment]
Got it

**Pull request closed without merging**
