### PR TITLE
Rc1.5/no initfile

### PR DESCRIPTION
**Pull request by twinkarma**
Removed requirement for initial states xml file. Changed `readInitialStates` so that it initialises all variables to the default value and then returns if no initial states file is found while printing a warning instead of terminating the program. 

When there's 0 agent count, the agent function belonging to the agent does not run.

Command line arguments stay the same for backward compatibility.

### CODE REVIEW

**Comment by ptheywood** [comment]
This seems to only total 7 changes, which are the removal of `\n` characters? 

Is this PR meant to be from your rc1.5/noinit branch instead (which has a commit on the 11th jul rather than just the 28th jun?

**Comment by mondus** [comment]
@twinkarma This is definitely an issue but I think you have merged the wrong branch as this only undoes Petes new  additions.

**Comment by ptheywood** [comment]
To confirm, this PR was for the wrong branch. I will create a new PR with the correct branch, and rebase etc to ensure that it will merge successfully.

**Comment by twinkarma** [comment]
Yes, look like it was the wrong branch after all so I've deleted it now.

**Pull request closed without merging**
